/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package railway;

/**
 *
 * @author Shyam Aditya
 */
public class mobile extends javax.swing.JFrame {

    /**
     * Creates new form mobile
     */
    public mobile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton8 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton8.setText("DEL");
        getContentPane().add(jButton8);
        jButton8.setBounds(470, 460, 60, 40);

        jLabel4.setFont(new java.awt.Font("NSimSun", 2, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setText("ENTER YOUR MOBILE NO:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(310, 230, 270, 40);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 102));
        jLabel2.setText("REPORTING SYSTEM");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 40, 340, 40);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 0, 102));
        jLabel3.setText("RAILWAY PROBLEM ANALYSIS & ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 0, 550, 40);

        jButton9.setText("8");
        getContentPane().add(jButton9);
        jButton9.setBounds(410, 420, 60, 40);

        jButton10.setText("AC");
        getContentPane().add(jButton10);
        jButton10.setBounds(350, 460, 60, 40);

        jButton11.setText("7");
        getContentPane().add(jButton11);
        jButton11.setBounds(350, 420, 60, 40);

        jButton12.setText("5");
        getContentPane().add(jButton12);
        jButton12.setBounds(410, 380, 60, 40);

        jButton13.setText("3");
        getContentPane().add(jButton13);
        jButton13.setBounds(470, 340, 60, 40);

        jButton14.setText("6");
        getContentPane().add(jButton14);
        jButton14.setBounds(470, 380, 60, 40);

        jButton15.setText("4");
        getContentPane().add(jButton15);
        jButton15.setBounds(350, 380, 60, 40);

        jButton16.setText("0");
        getContentPane().add(jButton16);
        jButton16.setBounds(410, 460, 60, 40);

        jButton17.setText("9");
        getContentPane().add(jButton17);
        jButton17.setBounds(470, 420, 60, 40);

        jButton18.setText("1");
        getContentPane().add(jButton18);
        jButton18.setBounds(350, 340, 60, 40);

        jButton19.setText("2");
        getContentPane().add(jButton19);
        jButton19.setBounds(410, 340, 60, 40);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(300, 280, 290, 40);

        jButton1.setText("SUBMIT");
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 530, 140, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/railway/zz.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-10, 0, 920, 620);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mobile.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mobile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
